// This file currently exists to prevent circular dependencies when extracting
// PLT functionality into its own package. The file name `kernel` is choosen
// in anticipation of more core definitions operating at the module/core
// intersection to follow.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: v2/concordium/kernel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An address of an account. Always 32 bytes.
type AccountAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountAddress) Reset() {
	*x = AccountAddress{}
	mi := &file_v2_concordium_kernel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountAddress) ProtoMessage() {}

func (x *AccountAddress) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_kernel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountAddress.ProtoReflect.Descriptor instead.
func (*AccountAddress) Descriptor() ([]byte, []int) {
	return file_v2_concordium_kernel_proto_rawDescGZIP(), []int{0}
}

func (x *AccountAddress) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// A memo which can be included as part of a transfer. Max size is 256 bytes.
type Memo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memo) Reset() {
	*x = Memo{}
	mi := &file_v2_concordium_kernel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memo) ProtoMessage() {}

func (x *Memo) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_kernel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memo.ProtoReflect.Descriptor instead.
func (*Memo) Descriptor() ([]byte, []int) {
	return file_v2_concordium_kernel_proto_rawDescGZIP(), []int{1}
}

func (x *Memo) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_v2_concordium_kernel_proto protoreflect.FileDescriptor

const file_v2_concordium_kernel_proto_rawDesc = "" +
	"\n" +
	"\x1av2/concordium/kernel.proto\x12\rconcordium.v2\"&\n" +
	"\x0eAccountAddress\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x1c\n" +
	"\x04Memo\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05valueB5\n" +
	"\x16com.concordium.grpc.v2P\x01Z\x04./pb\xaa\x02\x12Concordium.Grpc.V2b\x06proto3"

var (
	file_v2_concordium_kernel_proto_rawDescOnce sync.Once
	file_v2_concordium_kernel_proto_rawDescData []byte
)

func file_v2_concordium_kernel_proto_rawDescGZIP() []byte {
	file_v2_concordium_kernel_proto_rawDescOnce.Do(func() {
		file_v2_concordium_kernel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_concordium_kernel_proto_rawDesc), len(file_v2_concordium_kernel_proto_rawDesc)))
	})
	return file_v2_concordium_kernel_proto_rawDescData
}

var file_v2_concordium_kernel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v2_concordium_kernel_proto_goTypes = []any{
	(*AccountAddress)(nil), // 0: concordium.v2.AccountAddress
	(*Memo)(nil),           // 1: concordium.v2.Memo
}
var file_v2_concordium_kernel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v2_concordium_kernel_proto_init() }
func file_v2_concordium_kernel_proto_init() {
	if File_v2_concordium_kernel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_concordium_kernel_proto_rawDesc), len(file_v2_concordium_kernel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_concordium_kernel_proto_goTypes,
		DependencyIndexes: file_v2_concordium_kernel_proto_depIdxs,
		MessageInfos:      file_v2_concordium_kernel_proto_msgTypes,
	}.Build()
	File_v2_concordium_kernel_proto = out.File
	file_v2_concordium_kernel_proto_goTypes = nil
	file_v2_concordium_kernel_proto_depIdxs = nil
}
