// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: v2/concordium/protocol-level-tokens.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A CBOR encoded bytestring
type Cbor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A CBOR encoded byte string.
	Value         []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cbor) Reset() {
	*x = Cbor{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cbor) ProtoMessage() {}

func (x *Cbor) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cbor.ProtoReflect.Descriptor instead.
func (*Cbor) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{0}
}

func (x *Cbor) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Token ID: a unique symbol and identifier of a protocol level token.
type TokenId struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the token, guaranteed to be distinct across the
	// entire concordium blockchain. The token id must be between 1 and 128 bytes long and consist of
	// only a-z, A-Z, 0-9, `.`, `%` and `-`.
	Value         string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenId) Reset() {
	*x = TokenId{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenId) ProtoMessage() {}

func (x *TokenId) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenId.ProtoReflect.Descriptor instead.
func (*TokenId) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{1}
}

func (x *TokenId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A token module reference. This is always 32 bytes long.
type TokenModuleRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenModuleRef) Reset() {
	*x = TokenModuleRef{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenModuleRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenModuleRef) ProtoMessage() {}

func (x *TokenModuleRef) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenModuleRef.ProtoReflect.Descriptor instead.
func (*TokenModuleRef) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{2}
}

func (x *TokenModuleRef) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// PLT amount representation. The actual amount is computed as
// `value * 10^(-decimals)`.
type TokenAmount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The digits of the amount.
	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	// Number of decimals in the representation
	Decimals      uint32 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenAmount) Reset() {
	*x = TokenAmount{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAmount) ProtoMessage() {}

func (x *TokenAmount) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAmount.ProtoReflect.Descriptor instead.
func (*TokenAmount) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{3}
}

func (x *TokenAmount) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TokenAmount) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

// Token state at the block level
type TokenState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The reference of the module implementing this token.
	TokenModuleRef *TokenModuleRef `protobuf:"bytes,1,opt,name=token_module_ref,json=tokenModuleRef,proto3" json:"token_module_ref,omitempty"`
	// Number of decimals in the decimal number representation of amounts.
	Decimals uint32 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// The total available token supply.
	TotalSupply *TokenAmount `protobuf:"bytes,4,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	// Token module specific state, such as token name, feature flags, meta data.
	ModuleState   *Cbor `protobuf:"bytes,5,opt,name=module_state,json=moduleState,proto3" json:"module_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenState) Reset() {
	*x = TokenState{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenState) ProtoMessage() {}

func (x *TokenState) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenState.ProtoReflect.Descriptor instead.
func (*TokenState) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{4}
}

func (x *TokenState) GetTokenModuleRef() *TokenModuleRef {
	if x != nil {
		return x.TokenModuleRef
	}
	return nil
}

func (x *TokenState) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenState) GetTotalSupply() *TokenAmount {
	if x != nil {
		return x.TotalSupply
	}
	return nil
}

func (x *TokenState) GetModuleState() *Cbor {
	if x != nil {
		return x.ModuleState
	}
	return nil
}

// Token state at the account level
type TokenAccountState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The available balance.
	Balance *TokenAmount `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	// Token module specific account state, such as whether the account is on
	// the allow or deny list.
	ModuleState   *Cbor `protobuf:"bytes,4,opt,name=module_state,json=moduleState,proto3,oneof" json:"module_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenAccountState) Reset() {
	*x = TokenAccountState{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenAccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAccountState) ProtoMessage() {}

func (x *TokenAccountState) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAccountState.ProtoReflect.Descriptor instead.
func (*TokenAccountState) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{5}
}

func (x *TokenAccountState) GetBalance() *TokenAmount {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *TokenAccountState) GetModuleState() *Cbor {
	if x != nil {
		return x.ModuleState
	}
	return nil
}

// Single token event originating from a token module as part of a token
// transaction.
type TokenModuleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the event.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The CBOR encoded event details.
	Details       *Cbor `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenModuleEvent) Reset() {
	*x = TokenModuleEvent{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenModuleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenModuleEvent) ProtoMessage() {}

func (x *TokenModuleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenModuleEvent.ProtoReflect.Descriptor instead.
func (*TokenModuleEvent) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{6}
}

func (x *TokenModuleEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TokenModuleEvent) GetDetails() *Cbor {
	if x != nil {
		return x.Details
	}
	return nil
}

// A token holder is an entity that can hold tokens. Currently, this is limited
// to accounts, but in the future it may be extended to other entities.
type TokenHolder struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The holder address
	//
	// Types that are valid to be assigned to Address:
	//
	//	*TokenHolder_Account
	Address       isTokenHolder_Address `protobuf_oneof:"address"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenHolder) Reset() {
	*x = TokenHolder{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenHolder) ProtoMessage() {}

func (x *TokenHolder) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenHolder.ProtoReflect.Descriptor instead.
func (*TokenHolder) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{7}
}

func (x *TokenHolder) GetAddress() isTokenHolder_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TokenHolder) GetAccount() *AccountAddress {
	if x != nil {
		if x, ok := x.Address.(*TokenHolder_Account); ok {
			return x.Account
		}
	}
	return nil
}

type isTokenHolder_Address interface {
	isTokenHolder_Address()
}

type TokenHolder_Account struct {
	// The account address of the holder.
	Account *AccountAddress `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

func (*TokenHolder_Account) isTokenHolder_Address() {}

// An event emitted when a transfer of tokens from `from` to `to` is performed.
type TokenTransferEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token holder from which the tokens are transferred.
	From *TokenHolder `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// The token holder to which the tokens are transferred.
	To *TokenHolder `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// The amount of tokens transferred.
	Amount *TokenAmount `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	// An optional memo field that can be used to attach a message to the token
	// transfer.
	Memo          *Memo `protobuf:"bytes,4,opt,name=memo,proto3,oneof" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenTransferEvent) Reset() {
	*x = TokenTransferEvent{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenTransferEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenTransferEvent) ProtoMessage() {}

func (x *TokenTransferEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenTransferEvent.ProtoReflect.Descriptor instead.
func (*TokenTransferEvent) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{8}
}

func (x *TokenTransferEvent) GetFrom() *TokenHolder {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *TokenTransferEvent) GetTo() *TokenHolder {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TokenTransferEvent) GetAmount() *TokenAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *TokenTransferEvent) GetMemo() *Memo {
	if x != nil {
		return x.Memo
	}
	return nil
}

// An event emitted when the token supply is updated, i.e. by minting/burning
// tokens to/from the balance of the `target`.
type TokenSupplyUpdateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token holder the balance update is performed on.
	Target *TokenHolder `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// The balance difference to be applied to the target.
	Amount        *TokenAmount `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenSupplyUpdateEvent) Reset() {
	*x = TokenSupplyUpdateEvent{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenSupplyUpdateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenSupplyUpdateEvent) ProtoMessage() {}

func (x *TokenSupplyUpdateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenSupplyUpdateEvent.ProtoReflect.Descriptor instead.
func (*TokenSupplyUpdateEvent) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{9}
}

func (x *TokenSupplyUpdateEvent) GetTarget() *TokenHolder {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *TokenSupplyUpdateEvent) GetAmount() *TokenAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

// Token event originating from token transactions.
type TokenEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Token ID.
	TokenId *TokenId `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The type of the event.
	//
	// Types that are valid to be assigned to Event:
	//
	//	*TokenEvent_ModuleEvent
	//	*TokenEvent_TransferEvent
	//	*TokenEvent_MintEvent
	//	*TokenEvent_BurnEvent
	Event         isTokenEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenEvent) Reset() {
	*x = TokenEvent{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEvent) ProtoMessage() {}

func (x *TokenEvent) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEvent.ProtoReflect.Descriptor instead.
func (*TokenEvent) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{10}
}

func (x *TokenEvent) GetTokenId() *TokenId {
	if x != nil {
		return x.TokenId
	}
	return nil
}

func (x *TokenEvent) GetEvent() isTokenEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *TokenEvent) GetModuleEvent() *TokenModuleEvent {
	if x != nil {
		if x, ok := x.Event.(*TokenEvent_ModuleEvent); ok {
			return x.ModuleEvent
		}
	}
	return nil
}

func (x *TokenEvent) GetTransferEvent() *TokenTransferEvent {
	if x != nil {
		if x, ok := x.Event.(*TokenEvent_TransferEvent); ok {
			return x.TransferEvent
		}
	}
	return nil
}

func (x *TokenEvent) GetMintEvent() *TokenSupplyUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*TokenEvent_MintEvent); ok {
			return x.MintEvent
		}
	}
	return nil
}

func (x *TokenEvent) GetBurnEvent() *TokenSupplyUpdateEvent {
	if x != nil {
		if x, ok := x.Event.(*TokenEvent_BurnEvent); ok {
			return x.BurnEvent
		}
	}
	return nil
}

type isTokenEvent_Event interface {
	isTokenEvent_Event()
}

type TokenEvent_ModuleEvent struct {
	// An event emitted by the token module.
	ModuleEvent *TokenModuleEvent `protobuf:"bytes,2,opt,name=module_event,json=moduleEvent,proto3,oneof"`
}

type TokenEvent_TransferEvent struct {
	// An event emitted when a transfer of tokens is performed.
	TransferEvent *TokenTransferEvent `protobuf:"bytes,3,opt,name=transfer_event,json=transferEvent,proto3,oneof"`
}

type TokenEvent_MintEvent struct {
	// An event emitted when the token supply is updated by minting tokens to a
	// token holder.
	MintEvent *TokenSupplyUpdateEvent `protobuf:"bytes,4,opt,name=mint_event,json=mintEvent,proto3,oneof"`
}

type TokenEvent_BurnEvent struct {
	// An event emitted when the token supply is updated by burning tokens from
	// the balance of a token holder.
	BurnEvent *TokenSupplyUpdateEvent `protobuf:"bytes,5,opt,name=burn_event,json=burnEvent,proto3,oneof"`
}

func (*TokenEvent_ModuleEvent) isTokenEvent_Event() {}

func (*TokenEvent_TransferEvent) isTokenEvent_Event() {}

func (*TokenEvent_MintEvent) isTokenEvent_Event() {}

func (*TokenEvent_BurnEvent) isTokenEvent_Event() {}

// Token events originating from token transactions.
type TokenEffect struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events emitted by the token.
	Events        []*TokenEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenEffect) Reset() {
	*x = TokenEffect{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenEffect) ProtoMessage() {}

func (x *TokenEffect) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenEffect.ProtoReflect.Descriptor instead.
func (*TokenEffect) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{11}
}

func (x *TokenEffect) GetEvents() []*TokenEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Details provided by the token module in the event of rejecting a transaction.
type TokenModuleRejectReason struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Token ID of the protocol-level token.
	TokenId *TokenId `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The type of the reject reason.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// (Optional) CBOR-encoded details.
	Details       *Cbor `protobuf:"bytes,3,opt,name=details,proto3,oneof" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenModuleRejectReason) Reset() {
	*x = TokenModuleRejectReason{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenModuleRejectReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenModuleRejectReason) ProtoMessage() {}

func (x *TokenModuleRejectReason) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenModuleRejectReason.ProtoReflect.Descriptor instead.
func (*TokenModuleRejectReason) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{12}
}

func (x *TokenModuleRejectReason) GetTokenId() *TokenId {
	if x != nil {
		return x.TokenId
	}
	return nil
}

func (x *TokenModuleRejectReason) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TokenModuleRejectReason) GetDetails() *Cbor {
	if x != nil {
		return x.Details
	}
	return nil
}

// Update payload for creating a new protocol-level token
type CreatePLT struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Token ID of the protocol-level token.
	TokenId *TokenId `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	// The hash that identifies the token module implementation.
	TokenModule *TokenModuleRef `protobuf:"bytes,2,opt,name=token_module,json=tokenModule,proto3" json:"token_module,omitempty"`
	// The number of decimal places used in the representation of amounts of this
	// token. This determines the smallest representable fraction of the token.
	// This can be at most 255.
	Decimals uint32 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// The initialization parameters of the token, encoded in CBOR.
	InitializationParameters *Cbor `protobuf:"bytes,5,opt,name=initialization_parameters,json=initializationParameters,proto3" json:"initialization_parameters,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreatePLT) Reset() {
	*x = CreatePLT{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePLT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePLT) ProtoMessage() {}

func (x *CreatePLT) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePLT.ProtoReflect.Descriptor instead.
func (*CreatePLT) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePLT) GetTokenId() *TokenId {
	if x != nil {
		return x.TokenId
	}
	return nil
}

func (x *CreatePLT) GetTokenModule() *TokenModuleRef {
	if x != nil {
		return x.TokenModule
	}
	return nil
}

func (x *CreatePLT) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreatePLT) GetInitializationParameters() *Cbor {
	if x != nil {
		return x.InitializationParameters
	}
	return nil
}

// Details about the creation of a protocol-level token.
type TokenCreationDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The update payload used to create the token.
	CreatePlt *CreatePLT `protobuf:"bytes,1,opt,name=create_plt,json=createPlt,proto3" json:"create_plt,omitempty"`
	// The events generated by the token module during the creation of the token.
	Events        []*TokenEvent `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenCreationDetails) Reset() {
	*x = TokenCreationDetails{}
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenCreationDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenCreationDetails) ProtoMessage() {}

func (x *TokenCreationDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v2_concordium_protocol_level_tokens_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenCreationDetails.ProtoReflect.Descriptor instead.
func (*TokenCreationDetails) Descriptor() ([]byte, []int) {
	return file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP(), []int{14}
}

func (x *TokenCreationDetails) GetCreatePlt() *CreatePLT {
	if x != nil {
		return x.CreatePlt
	}
	return nil
}

func (x *TokenCreationDetails) GetEvents() []*TokenEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_v2_concordium_protocol_level_tokens_proto protoreflect.FileDescriptor

const file_v2_concordium_protocol_level_tokens_proto_rawDesc = "" +
	"\n" +
	")v2/concordium/protocol-level-tokens.proto\x12\x11concordium.v2.plt\x1a\x1av2/concordium/kernel.proto\"\x1c\n" +
	"\x04Cbor\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"\x1f\n" +
	"\aTokenId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\x0eTokenModuleRef\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\"?\n" +
	"\vTokenAmount\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x04R\x05value\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\"\xfa\x01\n" +
	"\n" +
	"TokenState\x12K\n" +
	"\x10token_module_ref\x18\x01 \x01(\v2!.concordium.v2.plt.TokenModuleRefR\x0etokenModuleRef\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12A\n" +
	"\ftotal_supply\x18\x04 \x01(\v2\x1e.concordium.v2.plt.TokenAmountR\vtotalSupply\x12:\n" +
	"\fmodule_state\x18\x05 \x01(\v2\x17.concordium.v2.plt.CborR\vmoduleStateJ\x04\b\x02\x10\x03\"\xab\x01\n" +
	"\x11TokenAccountState\x128\n" +
	"\abalance\x18\x01 \x01(\v2\x1e.concordium.v2.plt.TokenAmountR\abalance\x12?\n" +
	"\fmodule_state\x18\x04 \x01(\v2\x17.concordium.v2.plt.CborH\x00R\vmoduleState\x88\x01\x01B\x0f\n" +
	"\r_module_stateJ\x04\b\x02\x10\x03J\x04\b\x03\x10\x04\"Y\n" +
	"\x10TokenModuleEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x121\n" +
	"\adetails\x18\x02 \x01(\v2\x17.concordium.v2.plt.CborR\adetails\"S\n" +
	"\vTokenHolder\x129\n" +
	"\aaccount\x18\x01 \x01(\v2\x1d.concordium.v2.AccountAddressH\x00R\aaccountB\t\n" +
	"\aaddress\"\xe7\x01\n" +
	"\x12TokenTransferEvent\x122\n" +
	"\x04from\x18\x01 \x01(\v2\x1e.concordium.v2.plt.TokenHolderR\x04from\x12.\n" +
	"\x02to\x18\x02 \x01(\v2\x1e.concordium.v2.plt.TokenHolderR\x02to\x126\n" +
	"\x06amount\x18\x03 \x01(\v2\x1e.concordium.v2.plt.TokenAmountR\x06amount\x12,\n" +
	"\x04memo\x18\x04 \x01(\v2\x13.concordium.v2.MemoH\x00R\x04memo\x88\x01\x01B\a\n" +
	"\x05_memo\"\x88\x01\n" +
	"\x16TokenSupplyUpdateEvent\x126\n" +
	"\x06target\x18\x01 \x01(\v2\x1e.concordium.v2.plt.TokenHolderR\x06target\x126\n" +
	"\x06amount\x18\x02 \x01(\v2\x1e.concordium.v2.plt.TokenAmountR\x06amount\"\xfe\x02\n" +
	"\n" +
	"TokenEvent\x125\n" +
	"\btoken_id\x18\x01 \x01(\v2\x1a.concordium.v2.plt.TokenIdR\atokenId\x12H\n" +
	"\fmodule_event\x18\x02 \x01(\v2#.concordium.v2.plt.TokenModuleEventH\x00R\vmoduleEvent\x12N\n" +
	"\x0etransfer_event\x18\x03 \x01(\v2%.concordium.v2.plt.TokenTransferEventH\x00R\rtransferEvent\x12J\n" +
	"\n" +
	"mint_event\x18\x04 \x01(\v2).concordium.v2.plt.TokenSupplyUpdateEventH\x00R\tmintEvent\x12J\n" +
	"\n" +
	"burn_event\x18\x05 \x01(\v2).concordium.v2.plt.TokenSupplyUpdateEventH\x00R\tburnEventB\a\n" +
	"\x05event\"D\n" +
	"\vTokenEffect\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.concordium.v2.plt.TokenEventR\x06events\"\xa8\x01\n" +
	"\x17TokenModuleRejectReason\x125\n" +
	"\btoken_id\x18\x01 \x01(\v2\x1a.concordium.v2.plt.TokenIdR\atokenId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x126\n" +
	"\adetails\x18\x03 \x01(\v2\x17.concordium.v2.plt.CborH\x00R\adetails\x88\x01\x01B\n" +
	"\n" +
	"\b_details\"\x80\x02\n" +
	"\tCreatePLT\x125\n" +
	"\btoken_id\x18\x01 \x01(\v2\x1a.concordium.v2.plt.TokenIdR\atokenId\x12D\n" +
	"\ftoken_module\x18\x02 \x01(\v2!.concordium.v2.plt.TokenModuleRefR\vtokenModule\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals\x12T\n" +
	"\x19initialization_parameters\x18\x05 \x01(\v2\x17.concordium.v2.plt.CborR\x18initializationParametersJ\x04\b\x03\x10\x04\"\x8a\x01\n" +
	"\x14TokenCreationDetails\x12;\n" +
	"\n" +
	"create_plt\x18\x01 \x01(\v2\x1c.concordium.v2.plt.CreatePLTR\tcreatePlt\x125\n" +
	"\x06events\x18\x02 \x03(\v2\x1d.concordium.v2.plt.TokenEventR\x06eventsB=\n" +
	"\x1acom.concordium.grpc.v2.pltP\x01Z\x04./pb\xaa\x02\x16Concordium.Grpc.V2.Pltb\x06proto3"

var (
	file_v2_concordium_protocol_level_tokens_proto_rawDescOnce sync.Once
	file_v2_concordium_protocol_level_tokens_proto_rawDescData []byte
)

func file_v2_concordium_protocol_level_tokens_proto_rawDescGZIP() []byte {
	file_v2_concordium_protocol_level_tokens_proto_rawDescOnce.Do(func() {
		file_v2_concordium_protocol_level_tokens_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v2_concordium_protocol_level_tokens_proto_rawDesc), len(file_v2_concordium_protocol_level_tokens_proto_rawDesc)))
	})
	return file_v2_concordium_protocol_level_tokens_proto_rawDescData
}

var file_v2_concordium_protocol_level_tokens_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_v2_concordium_protocol_level_tokens_proto_goTypes = []any{
	(*Cbor)(nil),                    // 0: concordium.v2.plt.Cbor
	(*TokenId)(nil),                 // 1: concordium.v2.plt.TokenId
	(*TokenModuleRef)(nil),          // 2: concordium.v2.plt.TokenModuleRef
	(*TokenAmount)(nil),             // 3: concordium.v2.plt.TokenAmount
	(*TokenState)(nil),              // 4: concordium.v2.plt.TokenState
	(*TokenAccountState)(nil),       // 5: concordium.v2.plt.TokenAccountState
	(*TokenModuleEvent)(nil),        // 6: concordium.v2.plt.TokenModuleEvent
	(*TokenHolder)(nil),             // 7: concordium.v2.plt.TokenHolder
	(*TokenTransferEvent)(nil),      // 8: concordium.v2.plt.TokenTransferEvent
	(*TokenSupplyUpdateEvent)(nil),  // 9: concordium.v2.plt.TokenSupplyUpdateEvent
	(*TokenEvent)(nil),              // 10: concordium.v2.plt.TokenEvent
	(*TokenEffect)(nil),             // 11: concordium.v2.plt.TokenEffect
	(*TokenModuleRejectReason)(nil), // 12: concordium.v2.plt.TokenModuleRejectReason
	(*CreatePLT)(nil),               // 13: concordium.v2.plt.CreatePLT
	(*TokenCreationDetails)(nil),    // 14: concordium.v2.plt.TokenCreationDetails
	(*AccountAddress)(nil),          // 15: concordium.v2.AccountAddress
	(*Memo)(nil),                    // 16: concordium.v2.Memo
}
var file_v2_concordium_protocol_level_tokens_proto_depIdxs = []int32{
	2,  // 0: concordium.v2.plt.TokenState.token_module_ref:type_name -> concordium.v2.plt.TokenModuleRef
	3,  // 1: concordium.v2.plt.TokenState.total_supply:type_name -> concordium.v2.plt.TokenAmount
	0,  // 2: concordium.v2.plt.TokenState.module_state:type_name -> concordium.v2.plt.Cbor
	3,  // 3: concordium.v2.plt.TokenAccountState.balance:type_name -> concordium.v2.plt.TokenAmount
	0,  // 4: concordium.v2.plt.TokenAccountState.module_state:type_name -> concordium.v2.plt.Cbor
	0,  // 5: concordium.v2.plt.TokenModuleEvent.details:type_name -> concordium.v2.plt.Cbor
	15, // 6: concordium.v2.plt.TokenHolder.account:type_name -> concordium.v2.AccountAddress
	7,  // 7: concordium.v2.plt.TokenTransferEvent.from:type_name -> concordium.v2.plt.TokenHolder
	7,  // 8: concordium.v2.plt.TokenTransferEvent.to:type_name -> concordium.v2.plt.TokenHolder
	3,  // 9: concordium.v2.plt.TokenTransferEvent.amount:type_name -> concordium.v2.plt.TokenAmount
	16, // 10: concordium.v2.plt.TokenTransferEvent.memo:type_name -> concordium.v2.Memo
	7,  // 11: concordium.v2.plt.TokenSupplyUpdateEvent.target:type_name -> concordium.v2.plt.TokenHolder
	3,  // 12: concordium.v2.plt.TokenSupplyUpdateEvent.amount:type_name -> concordium.v2.plt.TokenAmount
	1,  // 13: concordium.v2.plt.TokenEvent.token_id:type_name -> concordium.v2.plt.TokenId
	6,  // 14: concordium.v2.plt.TokenEvent.module_event:type_name -> concordium.v2.plt.TokenModuleEvent
	8,  // 15: concordium.v2.plt.TokenEvent.transfer_event:type_name -> concordium.v2.plt.TokenTransferEvent
	9,  // 16: concordium.v2.plt.TokenEvent.mint_event:type_name -> concordium.v2.plt.TokenSupplyUpdateEvent
	9,  // 17: concordium.v2.plt.TokenEvent.burn_event:type_name -> concordium.v2.plt.TokenSupplyUpdateEvent
	10, // 18: concordium.v2.plt.TokenEffect.events:type_name -> concordium.v2.plt.TokenEvent
	1,  // 19: concordium.v2.plt.TokenModuleRejectReason.token_id:type_name -> concordium.v2.plt.TokenId
	0,  // 20: concordium.v2.plt.TokenModuleRejectReason.details:type_name -> concordium.v2.plt.Cbor
	1,  // 21: concordium.v2.plt.CreatePLT.token_id:type_name -> concordium.v2.plt.TokenId
	2,  // 22: concordium.v2.plt.CreatePLT.token_module:type_name -> concordium.v2.plt.TokenModuleRef
	0,  // 23: concordium.v2.plt.CreatePLT.initialization_parameters:type_name -> concordium.v2.plt.Cbor
	13, // 24: concordium.v2.plt.TokenCreationDetails.create_plt:type_name -> concordium.v2.plt.CreatePLT
	10, // 25: concordium.v2.plt.TokenCreationDetails.events:type_name -> concordium.v2.plt.TokenEvent
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_v2_concordium_protocol_level_tokens_proto_init() }
func file_v2_concordium_protocol_level_tokens_proto_init() {
	if File_v2_concordium_protocol_level_tokens_proto != nil {
		return
	}
	file_v2_concordium_kernel_proto_init()
	file_v2_concordium_protocol_level_tokens_proto_msgTypes[5].OneofWrappers = []any{}
	file_v2_concordium_protocol_level_tokens_proto_msgTypes[7].OneofWrappers = []any{
		(*TokenHolder_Account)(nil),
	}
	file_v2_concordium_protocol_level_tokens_proto_msgTypes[8].OneofWrappers = []any{}
	file_v2_concordium_protocol_level_tokens_proto_msgTypes[10].OneofWrappers = []any{
		(*TokenEvent_ModuleEvent)(nil),
		(*TokenEvent_TransferEvent)(nil),
		(*TokenEvent_MintEvent)(nil),
		(*TokenEvent_BurnEvent)(nil),
	}
	file_v2_concordium_protocol_level_tokens_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_concordium_protocol_level_tokens_proto_rawDesc), len(file_v2_concordium_protocol_level_tokens_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v2_concordium_protocol_level_tokens_proto_goTypes,
		DependencyIndexes: file_v2_concordium_protocol_level_tokens_proto_depIdxs,
		MessageInfos:      file_v2_concordium_protocol_level_tokens_proto_msgTypes,
	}.Build()
	File_v2_concordium_protocol_level_tokens_proto = out.File
	file_v2_concordium_protocol_level_tokens_proto_goTypes = nil
	file_v2_concordium_protocol_level_tokens_proto_depIdxs = nil
}
