// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: v2/concordium/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_v2_concordium_service_proto protoreflect.FileDescriptor

const file_v2_concordium_service_proto_rawDesc = "" +
	"\n" +
	"\x1bv2/concordium/service.proto\x12\rconcordium.v2\x1a\x1av2/concordium/kernel.proto\x1a\x19v2/concordium/types.proto\x1a)v2/concordium/protocol-level-tokens.proto2\xc8)\n" +
	"\aQueries\x12D\n" +
	"\tGetBlocks\x12\x14.concordium.v2.Empty\x1a\x1f.concordium.v2.ArrivedBlockInfo0\x01\x12O\n" +
	"\x12GetFinalizedBlocks\x12\x14.concordium.v2.Empty\x1a!.concordium.v2.FinalizedBlockInfo0\x01\x12O\n" +
	"\x0eGetAccountInfo\x12!.concordium.v2.AccountInfoRequest\x1a\x1a.concordium.v2.AccountInfo\x12I\n" +
	"\fGetTokenInfo\x12\x1f.concordium.v2.TokenInfoRequest\x1a\x18.concordium.v2.TokenInfo\x12P\n" +
	"\x0eGetAccountList\x12\x1d.concordium.v2.BlockHashInput\x1a\x1d.concordium.v2.AccountAddress0\x01\x12K\n" +
	"\fGetTokenList\x12\x1d.concordium.v2.BlockHashInput\x1a\x1a.concordium.v2.plt.TokenId0\x01\x12J\n" +
	"\rGetModuleList\x12\x1d.concordium.v2.BlockHashInput\x1a\x18.concordium.v2.ModuleRef0\x01\x12K\n" +
	"\fGetAncestors\x12\x1f.concordium.v2.AncestorsRequest\x1a\x18.concordium.v2.BlockHash0\x01\x12[\n" +
	"\x0fGetModuleSource\x12\".concordium.v2.ModuleSourceRequest\x1a$.concordium.v2.VersionedModuleSource\x12R\n" +
	"\x0fGetInstanceList\x12\x1d.concordium.v2.BlockHashInput\x1a\x1e.concordium.v2.ContractAddress0\x01\x12R\n" +
	"\x0fGetInstanceInfo\x12\".concordium.v2.InstanceInfoRequest\x1a\x1b.concordium.v2.InstanceInfo\x12\\\n" +
	"\x10GetInstanceState\x12\".concordium.v2.InstanceInfoRequest\x1a\".concordium.v2.InstanceStateKVPair0\x01\x12h\n" +
	"\x13InstanceStateLookup\x12).concordium.v2.InstanceStateLookupRequest\x1a&.concordium.v2.InstanceStateValueAtKey\x12g\n" +
	"\x1cGetNextAccountSequenceNumber\x12\x1d.concordium.v2.AccountAddress\x1a(.concordium.v2.NextAccountSequenceNumber\x12F\n" +
	"\x10GetConsensusInfo\x12\x14.concordium.v2.Empty\x1a\x1c.concordium.v2.ConsensusInfo\x12T\n" +
	"\x12GetBlockItemStatus\x12\x1e.concordium.v2.TransactionHash\x1a\x1e.concordium.v2.BlockItemStatus\x12c\n" +
	"\x1aGetCryptographicParameters\x12\x1d.concordium.v2.BlockHashInput\x1a&.concordium.v2.CryptographicParameters\x12G\n" +
	"\fGetBlockInfo\x12\x1d.concordium.v2.BlockHashInput\x1a\x18.concordium.v2.BlockInfo\x12G\n" +
	"\fGetBakerList\x12\x1d.concordium.v2.BlockHashInput\x1a\x16.concordium.v2.BakerId0\x01\x12N\n" +
	"\vGetPoolInfo\x12\x1e.concordium.v2.PoolInfoRequest\x1a\x1f.concordium.v2.PoolInfoResponse\x12_\n" +
	"\x18GetPassiveDelegationInfo\x12\x1d.concordium.v2.BlockHashInput\x1a$.concordium.v2.PassiveDelegationInfo\x12`\n" +
	"\x11GetBlocksAtHeight\x12$.concordium.v2.BlocksAtHeightRequest\x1a%.concordium.v2.BlocksAtHeightResponse\x12Q\n" +
	"\x11GetTokenomicsInfo\x12\x1d.concordium.v2.BlockHashInput\x1a\x1d.concordium.v2.TokenomicsInfo\x12]\n" +
	"\x0eInvokeInstance\x12$.concordium.v2.InvokeInstanceRequest\x1a%.concordium.v2.InvokeInstanceResponse\x12\\\n" +
	"\x11GetPoolDelegators\x12'.concordium.v2.GetPoolDelegatorsRequest\x1a\x1c.concordium.v2.DelegatorInfo0\x01\x12t\n" +
	"\x1dGetPoolDelegatorsRewardPeriod\x12'.concordium.v2.GetPoolDelegatorsRequest\x1a(.concordium.v2.DelegatorRewardPeriodInfo0\x01\x12U\n" +
	"\x14GetPassiveDelegators\x12\x1d.concordium.v2.BlockHashInput\x1a\x1c.concordium.v2.DelegatorInfo0\x01\x12m\n" +
	" GetPassiveDelegatorsRewardPeriod\x12\x1d.concordium.v2.BlockHashInput\x1a(.concordium.v2.DelegatorRewardPeriodInfo0\x01\x12:\n" +
	"\vGetBranches\x12\x14.concordium.v2.Empty\x1a\x15.concordium.v2.Branch\x12M\n" +
	"\x0fGetElectionInfo\x12\x1d.concordium.v2.BlockHashInput\x1a\x1b.concordium.v2.ElectionInfo\x12N\n" +
	"\x14GetIdentityProviders\x12\x1d.concordium.v2.BlockHashInput\x1a\x15.concordium.v2.IpInfo0\x01\x12N\n" +
	"\x14GetAnonymityRevokers\x12\x1d.concordium.v2.BlockHashInput\x1a\x15.concordium.v2.ArInfo0\x01\x12e\n" +
	"\"GetAccountNonFinalizedTransactions\x12\x1d.concordium.v2.AccountAddress\x1a\x1e.concordium.v2.TransactionHash0\x01\x12]\n" +
	"\x19GetBlockTransactionEvents\x12\x1d.concordium.v2.BlockHashInput\x1a\x1f.concordium.v2.BlockItemSummary0\x01\x12Z\n" +
	"\x15GetBlockSpecialEvents\x12\x1d.concordium.v2.BlockHashInput\x1a .concordium.v2.BlockSpecialEvent0\x01\x12W\n" +
	"\x16GetBlockPendingUpdates\x12\x1d.concordium.v2.BlockHashInput\x1a\x1c.concordium.v2.PendingUpdate0\x01\x12g\n" +
	"\x1cGetNextUpdateSequenceNumbers\x12\x1d.concordium.v2.BlockHashInput\x1a(.concordium.v2.NextUpdateSequenceNumbers\x12]\n" +
	"\x1bGetScheduledReleaseAccounts\x12\x1d.concordium.v2.BlockHashInput\x1a\x1d.concordium.v2.AccountPending0\x01\x12U\n" +
	"\x13GetCooldownAccounts\x12\x1d.concordium.v2.BlockHashInput\x1a\x1d.concordium.v2.AccountPending0\x01\x12V\n" +
	"\x16GetPreCooldownAccounts\x12\x1d.concordium.v2.BlockHashInput\x1a\x1b.concordium.v2.AccountIndex0\x01\x12Y\n" +
	"\x19GetPrePreCooldownAccounts\x12\x1d.concordium.v2.BlockHashInput\x1a\x1b.concordium.v2.AccountIndex0\x01\x12K\n" +
	"\x17GetBakerEarliestWinTime\x12\x16.concordium.v2.BakerId\x1a\x18.concordium.v2.Timestamp\x126\n" +
	"\bShutdown\x12\x14.concordium.v2.Empty\x1a\x14.concordium.v2.Empty\x12C\n" +
	"\vPeerConnect\x12\x1e.concordium.v2.IpSocketAddress\x1a\x14.concordium.v2.Empty\x12F\n" +
	"\x0ePeerDisconnect\x12\x1e.concordium.v2.IpSocketAddress\x1a\x14.concordium.v2.Empty\x12B\n" +
	"\x0eGetBannedPeers\x12\x14.concordium.v2.Empty\x1a\x1a.concordium.v2.BannedPeers\x129\n" +
	"\aBanPeer\x12\x18.concordium.v2.PeerToBan\x1a\x14.concordium.v2.Empty\x12<\n" +
	"\tUnbanPeer\x12\x19.concordium.v2.BannedPeer\x1a\x14.concordium.v2.Empty\x12=\n" +
	"\tDumpStart\x12\x1a.concordium.v2.DumpRequest\x1a\x14.concordium.v2.Empty\x126\n" +
	"\bDumpStop\x12\x14.concordium.v2.Empty\x1a\x14.concordium.v2.Empty\x12>\n" +
	"\fGetPeersInfo\x12\x14.concordium.v2.Empty\x1a\x18.concordium.v2.PeersInfo\x12<\n" +
	"\vGetNodeInfo\x12\x14.concordium.v2.Empty\x1a\x17.concordium.v2.NodeInfo\x12T\n" +
	"\rSendBlockItem\x12#.concordium.v2.SendBlockItemRequest\x1a\x1e.concordium.v2.TransactionHash\x12p\n" +
	"\x1dGetAccountTransactionSignHash\x12$.concordium.v2.PreAccountTransaction\x1a).concordium.v2.AccountTransactionSignHash\x12X\n" +
	"\x17GetBlockChainParameters\x12\x1d.concordium.v2.BlockHashInput\x1a\x1e.concordium.v2.ChainParameters\x12e\n" +
	"\x1bGetBlockFinalizationSummary\x12\x1d.concordium.v2.BlockHashInput\x1a'.concordium.v2.BlockFinalizationSummary\x12J\n" +
	"\rGetBlockItems\x12\x1d.concordium.v2.BlockHashInput\x1a\x18.concordium.v2.BlockItem0\x01\x12^\n" +
	"\x15GetBakersRewardPeriod\x12\x1d.concordium.v2.BlockHashInput\x1a$.concordium.v2.BakerRewardPeriodInfo0\x01\x12W\n" +
	"\x14GetBlockCertificates\x12\x1d.concordium.v2.BlockHashInput\x1a .concordium.v2.BlockCertificates\x12S\n" +
	"\x15GetWinningBakersEpoch\x12\x1b.concordium.v2.EpochRequest\x1a\x1b.concordium.v2.WinningBaker0\x01\x12K\n" +
	"\x12GetFirstBlockEpoch\x12\x1b.concordium.v2.EpochRequest\x1a\x18.concordium.v2.BlockHash\x12q\n" +
	"\x1aGetConsensusDetailedStatus\x12+.concordium.v2.ConsensusDetailedStatusQuery\x1a&.concordium.v2.ConsensusDetailedStatus\x12I\n" +
	"\x06DryRun\x12\x1c.concordium.v2.DryRunRequest\x1a\x1d.concordium.v2.DryRunResponse(\x010\x01B5\n" +
	"\x16com.concordium.grpc.v2P\x01Z\x04./pb\xaa\x02\x12Concordium.Grpc.V2b\x06proto3"

var file_v2_concordium_service_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: concordium.v2.Empty
	(*AccountInfoRequest)(nil),           // 1: concordium.v2.AccountInfoRequest
	(*TokenInfoRequest)(nil),             // 2: concordium.v2.TokenInfoRequest
	(*BlockHashInput)(nil),               // 3: concordium.v2.BlockHashInput
	(*AncestorsRequest)(nil),             // 4: concordium.v2.AncestorsRequest
	(*ModuleSourceRequest)(nil),          // 5: concordium.v2.ModuleSourceRequest
	(*InstanceInfoRequest)(nil),          // 6: concordium.v2.InstanceInfoRequest
	(*InstanceStateLookupRequest)(nil),   // 7: concordium.v2.InstanceStateLookupRequest
	(*AccountAddress)(nil),               // 8: concordium.v2.AccountAddress
	(*TransactionHash)(nil),              // 9: concordium.v2.TransactionHash
	(*PoolInfoRequest)(nil),              // 10: concordium.v2.PoolInfoRequest
	(*BlocksAtHeightRequest)(nil),        // 11: concordium.v2.BlocksAtHeightRequest
	(*InvokeInstanceRequest)(nil),        // 12: concordium.v2.InvokeInstanceRequest
	(*GetPoolDelegatorsRequest)(nil),     // 13: concordium.v2.GetPoolDelegatorsRequest
	(*BakerId)(nil),                      // 14: concordium.v2.BakerId
	(*IpSocketAddress)(nil),              // 15: concordium.v2.IpSocketAddress
	(*PeerToBan)(nil),                    // 16: concordium.v2.PeerToBan
	(*BannedPeer)(nil),                   // 17: concordium.v2.BannedPeer
	(*DumpRequest)(nil),                  // 18: concordium.v2.DumpRequest
	(*SendBlockItemRequest)(nil),         // 19: concordium.v2.SendBlockItemRequest
	(*PreAccountTransaction)(nil),        // 20: concordium.v2.PreAccountTransaction
	(*EpochRequest)(nil),                 // 21: concordium.v2.EpochRequest
	(*ConsensusDetailedStatusQuery)(nil), // 22: concordium.v2.ConsensusDetailedStatusQuery
	(*DryRunRequest)(nil),                // 23: concordium.v2.DryRunRequest
	(*ArrivedBlockInfo)(nil),             // 24: concordium.v2.ArrivedBlockInfo
	(*FinalizedBlockInfo)(nil),           // 25: concordium.v2.FinalizedBlockInfo
	(*AccountInfo)(nil),                  // 26: concordium.v2.AccountInfo
	(*TokenInfo)(nil),                    // 27: concordium.v2.TokenInfo
	(*TokenId)(nil),                      // 28: concordium.v2.plt.TokenId
	(*ModuleRef)(nil),                    // 29: concordium.v2.ModuleRef
	(*BlockHash)(nil),                    // 30: concordium.v2.BlockHash
	(*VersionedModuleSource)(nil),        // 31: concordium.v2.VersionedModuleSource
	(*ContractAddress)(nil),              // 32: concordium.v2.ContractAddress
	(*InstanceInfo)(nil),                 // 33: concordium.v2.InstanceInfo
	(*InstanceStateKVPair)(nil),          // 34: concordium.v2.InstanceStateKVPair
	(*InstanceStateValueAtKey)(nil),      // 35: concordium.v2.InstanceStateValueAtKey
	(*NextAccountSequenceNumber)(nil),    // 36: concordium.v2.NextAccountSequenceNumber
	(*ConsensusInfo)(nil),                // 37: concordium.v2.ConsensusInfo
	(*BlockItemStatus)(nil),              // 38: concordium.v2.BlockItemStatus
	(*CryptographicParameters)(nil),      // 39: concordium.v2.CryptographicParameters
	(*BlockInfo)(nil),                    // 40: concordium.v2.BlockInfo
	(*PoolInfoResponse)(nil),             // 41: concordium.v2.PoolInfoResponse
	(*PassiveDelegationInfo)(nil),        // 42: concordium.v2.PassiveDelegationInfo
	(*BlocksAtHeightResponse)(nil),       // 43: concordium.v2.BlocksAtHeightResponse
	(*TokenomicsInfo)(nil),               // 44: concordium.v2.TokenomicsInfo
	(*InvokeInstanceResponse)(nil),       // 45: concordium.v2.InvokeInstanceResponse
	(*DelegatorInfo)(nil),                // 46: concordium.v2.DelegatorInfo
	(*DelegatorRewardPeriodInfo)(nil),    // 47: concordium.v2.DelegatorRewardPeriodInfo
	(*Branch)(nil),                       // 48: concordium.v2.Branch
	(*ElectionInfo)(nil),                 // 49: concordium.v2.ElectionInfo
	(*IpInfo)(nil),                       // 50: concordium.v2.IpInfo
	(*ArInfo)(nil),                       // 51: concordium.v2.ArInfo
	(*BlockItemSummary)(nil),             // 52: concordium.v2.BlockItemSummary
	(*BlockSpecialEvent)(nil),            // 53: concordium.v2.BlockSpecialEvent
	(*PendingUpdate)(nil),                // 54: concordium.v2.PendingUpdate
	(*NextUpdateSequenceNumbers)(nil),    // 55: concordium.v2.NextUpdateSequenceNumbers
	(*AccountPending)(nil),               // 56: concordium.v2.AccountPending
	(*AccountIndex)(nil),                 // 57: concordium.v2.AccountIndex
	(*Timestamp)(nil),                    // 58: concordium.v2.Timestamp
	(*BannedPeers)(nil),                  // 59: concordium.v2.BannedPeers
	(*PeersInfo)(nil),                    // 60: concordium.v2.PeersInfo
	(*NodeInfo)(nil),                     // 61: concordium.v2.NodeInfo
	(*AccountTransactionSignHash)(nil),   // 62: concordium.v2.AccountTransactionSignHash
	(*ChainParameters)(nil),              // 63: concordium.v2.ChainParameters
	(*BlockFinalizationSummary)(nil),     // 64: concordium.v2.BlockFinalizationSummary
	(*BlockItem)(nil),                    // 65: concordium.v2.BlockItem
	(*BakerRewardPeriodInfo)(nil),        // 66: concordium.v2.BakerRewardPeriodInfo
	(*BlockCertificates)(nil),            // 67: concordium.v2.BlockCertificates
	(*WinningBaker)(nil),                 // 68: concordium.v2.WinningBaker
	(*ConsensusDetailedStatus)(nil),      // 69: concordium.v2.ConsensusDetailedStatus
	(*DryRunResponse)(nil),               // 70: concordium.v2.DryRunResponse
}
var file_v2_concordium_service_proto_depIdxs = []int32{
	0,  // 0: concordium.v2.Queries.GetBlocks:input_type -> concordium.v2.Empty
	0,  // 1: concordium.v2.Queries.GetFinalizedBlocks:input_type -> concordium.v2.Empty
	1,  // 2: concordium.v2.Queries.GetAccountInfo:input_type -> concordium.v2.AccountInfoRequest
	2,  // 3: concordium.v2.Queries.GetTokenInfo:input_type -> concordium.v2.TokenInfoRequest
	3,  // 4: concordium.v2.Queries.GetAccountList:input_type -> concordium.v2.BlockHashInput
	3,  // 5: concordium.v2.Queries.GetTokenList:input_type -> concordium.v2.BlockHashInput
	3,  // 6: concordium.v2.Queries.GetModuleList:input_type -> concordium.v2.BlockHashInput
	4,  // 7: concordium.v2.Queries.GetAncestors:input_type -> concordium.v2.AncestorsRequest
	5,  // 8: concordium.v2.Queries.GetModuleSource:input_type -> concordium.v2.ModuleSourceRequest
	3,  // 9: concordium.v2.Queries.GetInstanceList:input_type -> concordium.v2.BlockHashInput
	6,  // 10: concordium.v2.Queries.GetInstanceInfo:input_type -> concordium.v2.InstanceInfoRequest
	6,  // 11: concordium.v2.Queries.GetInstanceState:input_type -> concordium.v2.InstanceInfoRequest
	7,  // 12: concordium.v2.Queries.InstanceStateLookup:input_type -> concordium.v2.InstanceStateLookupRequest
	8,  // 13: concordium.v2.Queries.GetNextAccountSequenceNumber:input_type -> concordium.v2.AccountAddress
	0,  // 14: concordium.v2.Queries.GetConsensusInfo:input_type -> concordium.v2.Empty
	9,  // 15: concordium.v2.Queries.GetBlockItemStatus:input_type -> concordium.v2.TransactionHash
	3,  // 16: concordium.v2.Queries.GetCryptographicParameters:input_type -> concordium.v2.BlockHashInput
	3,  // 17: concordium.v2.Queries.GetBlockInfo:input_type -> concordium.v2.BlockHashInput
	3,  // 18: concordium.v2.Queries.GetBakerList:input_type -> concordium.v2.BlockHashInput
	10, // 19: concordium.v2.Queries.GetPoolInfo:input_type -> concordium.v2.PoolInfoRequest
	3,  // 20: concordium.v2.Queries.GetPassiveDelegationInfo:input_type -> concordium.v2.BlockHashInput
	11, // 21: concordium.v2.Queries.GetBlocksAtHeight:input_type -> concordium.v2.BlocksAtHeightRequest
	3,  // 22: concordium.v2.Queries.GetTokenomicsInfo:input_type -> concordium.v2.BlockHashInput
	12, // 23: concordium.v2.Queries.InvokeInstance:input_type -> concordium.v2.InvokeInstanceRequest
	13, // 24: concordium.v2.Queries.GetPoolDelegators:input_type -> concordium.v2.GetPoolDelegatorsRequest
	13, // 25: concordium.v2.Queries.GetPoolDelegatorsRewardPeriod:input_type -> concordium.v2.GetPoolDelegatorsRequest
	3,  // 26: concordium.v2.Queries.GetPassiveDelegators:input_type -> concordium.v2.BlockHashInput
	3,  // 27: concordium.v2.Queries.GetPassiveDelegatorsRewardPeriod:input_type -> concordium.v2.BlockHashInput
	0,  // 28: concordium.v2.Queries.GetBranches:input_type -> concordium.v2.Empty
	3,  // 29: concordium.v2.Queries.GetElectionInfo:input_type -> concordium.v2.BlockHashInput
	3,  // 30: concordium.v2.Queries.GetIdentityProviders:input_type -> concordium.v2.BlockHashInput
	3,  // 31: concordium.v2.Queries.GetAnonymityRevokers:input_type -> concordium.v2.BlockHashInput
	8,  // 32: concordium.v2.Queries.GetAccountNonFinalizedTransactions:input_type -> concordium.v2.AccountAddress
	3,  // 33: concordium.v2.Queries.GetBlockTransactionEvents:input_type -> concordium.v2.BlockHashInput
	3,  // 34: concordium.v2.Queries.GetBlockSpecialEvents:input_type -> concordium.v2.BlockHashInput
	3,  // 35: concordium.v2.Queries.GetBlockPendingUpdates:input_type -> concordium.v2.BlockHashInput
	3,  // 36: concordium.v2.Queries.GetNextUpdateSequenceNumbers:input_type -> concordium.v2.BlockHashInput
	3,  // 37: concordium.v2.Queries.GetScheduledReleaseAccounts:input_type -> concordium.v2.BlockHashInput
	3,  // 38: concordium.v2.Queries.GetCooldownAccounts:input_type -> concordium.v2.BlockHashInput
	3,  // 39: concordium.v2.Queries.GetPreCooldownAccounts:input_type -> concordium.v2.BlockHashInput
	3,  // 40: concordium.v2.Queries.GetPrePreCooldownAccounts:input_type -> concordium.v2.BlockHashInput
	14, // 41: concordium.v2.Queries.GetBakerEarliestWinTime:input_type -> concordium.v2.BakerId
	0,  // 42: concordium.v2.Queries.Shutdown:input_type -> concordium.v2.Empty
	15, // 43: concordium.v2.Queries.PeerConnect:input_type -> concordium.v2.IpSocketAddress
	15, // 44: concordium.v2.Queries.PeerDisconnect:input_type -> concordium.v2.IpSocketAddress
	0,  // 45: concordium.v2.Queries.GetBannedPeers:input_type -> concordium.v2.Empty
	16, // 46: concordium.v2.Queries.BanPeer:input_type -> concordium.v2.PeerToBan
	17, // 47: concordium.v2.Queries.UnbanPeer:input_type -> concordium.v2.BannedPeer
	18, // 48: concordium.v2.Queries.DumpStart:input_type -> concordium.v2.DumpRequest
	0,  // 49: concordium.v2.Queries.DumpStop:input_type -> concordium.v2.Empty
	0,  // 50: concordium.v2.Queries.GetPeersInfo:input_type -> concordium.v2.Empty
	0,  // 51: concordium.v2.Queries.GetNodeInfo:input_type -> concordium.v2.Empty
	19, // 52: concordium.v2.Queries.SendBlockItem:input_type -> concordium.v2.SendBlockItemRequest
	20, // 53: concordium.v2.Queries.GetAccountTransactionSignHash:input_type -> concordium.v2.PreAccountTransaction
	3,  // 54: concordium.v2.Queries.GetBlockChainParameters:input_type -> concordium.v2.BlockHashInput
	3,  // 55: concordium.v2.Queries.GetBlockFinalizationSummary:input_type -> concordium.v2.BlockHashInput
	3,  // 56: concordium.v2.Queries.GetBlockItems:input_type -> concordium.v2.BlockHashInput
	3,  // 57: concordium.v2.Queries.GetBakersRewardPeriod:input_type -> concordium.v2.BlockHashInput
	3,  // 58: concordium.v2.Queries.GetBlockCertificates:input_type -> concordium.v2.BlockHashInput
	21, // 59: concordium.v2.Queries.GetWinningBakersEpoch:input_type -> concordium.v2.EpochRequest
	21, // 60: concordium.v2.Queries.GetFirstBlockEpoch:input_type -> concordium.v2.EpochRequest
	22, // 61: concordium.v2.Queries.GetConsensusDetailedStatus:input_type -> concordium.v2.ConsensusDetailedStatusQuery
	23, // 62: concordium.v2.Queries.DryRun:input_type -> concordium.v2.DryRunRequest
	24, // 63: concordium.v2.Queries.GetBlocks:output_type -> concordium.v2.ArrivedBlockInfo
	25, // 64: concordium.v2.Queries.GetFinalizedBlocks:output_type -> concordium.v2.FinalizedBlockInfo
	26, // 65: concordium.v2.Queries.GetAccountInfo:output_type -> concordium.v2.AccountInfo
	27, // 66: concordium.v2.Queries.GetTokenInfo:output_type -> concordium.v2.TokenInfo
	8,  // 67: concordium.v2.Queries.GetAccountList:output_type -> concordium.v2.AccountAddress
	28, // 68: concordium.v2.Queries.GetTokenList:output_type -> concordium.v2.plt.TokenId
	29, // 69: concordium.v2.Queries.GetModuleList:output_type -> concordium.v2.ModuleRef
	30, // 70: concordium.v2.Queries.GetAncestors:output_type -> concordium.v2.BlockHash
	31, // 71: concordium.v2.Queries.GetModuleSource:output_type -> concordium.v2.VersionedModuleSource
	32, // 72: concordium.v2.Queries.GetInstanceList:output_type -> concordium.v2.ContractAddress
	33, // 73: concordium.v2.Queries.GetInstanceInfo:output_type -> concordium.v2.InstanceInfo
	34, // 74: concordium.v2.Queries.GetInstanceState:output_type -> concordium.v2.InstanceStateKVPair
	35, // 75: concordium.v2.Queries.InstanceStateLookup:output_type -> concordium.v2.InstanceStateValueAtKey
	36, // 76: concordium.v2.Queries.GetNextAccountSequenceNumber:output_type -> concordium.v2.NextAccountSequenceNumber
	37, // 77: concordium.v2.Queries.GetConsensusInfo:output_type -> concordium.v2.ConsensusInfo
	38, // 78: concordium.v2.Queries.GetBlockItemStatus:output_type -> concordium.v2.BlockItemStatus
	39, // 79: concordium.v2.Queries.GetCryptographicParameters:output_type -> concordium.v2.CryptographicParameters
	40, // 80: concordium.v2.Queries.GetBlockInfo:output_type -> concordium.v2.BlockInfo
	14, // 81: concordium.v2.Queries.GetBakerList:output_type -> concordium.v2.BakerId
	41, // 82: concordium.v2.Queries.GetPoolInfo:output_type -> concordium.v2.PoolInfoResponse
	42, // 83: concordium.v2.Queries.GetPassiveDelegationInfo:output_type -> concordium.v2.PassiveDelegationInfo
	43, // 84: concordium.v2.Queries.GetBlocksAtHeight:output_type -> concordium.v2.BlocksAtHeightResponse
	44, // 85: concordium.v2.Queries.GetTokenomicsInfo:output_type -> concordium.v2.TokenomicsInfo
	45, // 86: concordium.v2.Queries.InvokeInstance:output_type -> concordium.v2.InvokeInstanceResponse
	46, // 87: concordium.v2.Queries.GetPoolDelegators:output_type -> concordium.v2.DelegatorInfo
	47, // 88: concordium.v2.Queries.GetPoolDelegatorsRewardPeriod:output_type -> concordium.v2.DelegatorRewardPeriodInfo
	46, // 89: concordium.v2.Queries.GetPassiveDelegators:output_type -> concordium.v2.DelegatorInfo
	47, // 90: concordium.v2.Queries.GetPassiveDelegatorsRewardPeriod:output_type -> concordium.v2.DelegatorRewardPeriodInfo
	48, // 91: concordium.v2.Queries.GetBranches:output_type -> concordium.v2.Branch
	49, // 92: concordium.v2.Queries.GetElectionInfo:output_type -> concordium.v2.ElectionInfo
	50, // 93: concordium.v2.Queries.GetIdentityProviders:output_type -> concordium.v2.IpInfo
	51, // 94: concordium.v2.Queries.GetAnonymityRevokers:output_type -> concordium.v2.ArInfo
	9,  // 95: concordium.v2.Queries.GetAccountNonFinalizedTransactions:output_type -> concordium.v2.TransactionHash
	52, // 96: concordium.v2.Queries.GetBlockTransactionEvents:output_type -> concordium.v2.BlockItemSummary
	53, // 97: concordium.v2.Queries.GetBlockSpecialEvents:output_type -> concordium.v2.BlockSpecialEvent
	54, // 98: concordium.v2.Queries.GetBlockPendingUpdates:output_type -> concordium.v2.PendingUpdate
	55, // 99: concordium.v2.Queries.GetNextUpdateSequenceNumbers:output_type -> concordium.v2.NextUpdateSequenceNumbers
	56, // 100: concordium.v2.Queries.GetScheduledReleaseAccounts:output_type -> concordium.v2.AccountPending
	56, // 101: concordium.v2.Queries.GetCooldownAccounts:output_type -> concordium.v2.AccountPending
	57, // 102: concordium.v2.Queries.GetPreCooldownAccounts:output_type -> concordium.v2.AccountIndex
	57, // 103: concordium.v2.Queries.GetPrePreCooldownAccounts:output_type -> concordium.v2.AccountIndex
	58, // 104: concordium.v2.Queries.GetBakerEarliestWinTime:output_type -> concordium.v2.Timestamp
	0,  // 105: concordium.v2.Queries.Shutdown:output_type -> concordium.v2.Empty
	0,  // 106: concordium.v2.Queries.PeerConnect:output_type -> concordium.v2.Empty
	0,  // 107: concordium.v2.Queries.PeerDisconnect:output_type -> concordium.v2.Empty
	59, // 108: concordium.v2.Queries.GetBannedPeers:output_type -> concordium.v2.BannedPeers
	0,  // 109: concordium.v2.Queries.BanPeer:output_type -> concordium.v2.Empty
	0,  // 110: concordium.v2.Queries.UnbanPeer:output_type -> concordium.v2.Empty
	0,  // 111: concordium.v2.Queries.DumpStart:output_type -> concordium.v2.Empty
	0,  // 112: concordium.v2.Queries.DumpStop:output_type -> concordium.v2.Empty
	60, // 113: concordium.v2.Queries.GetPeersInfo:output_type -> concordium.v2.PeersInfo
	61, // 114: concordium.v2.Queries.GetNodeInfo:output_type -> concordium.v2.NodeInfo
	9,  // 115: concordium.v2.Queries.SendBlockItem:output_type -> concordium.v2.TransactionHash
	62, // 116: concordium.v2.Queries.GetAccountTransactionSignHash:output_type -> concordium.v2.AccountTransactionSignHash
	63, // 117: concordium.v2.Queries.GetBlockChainParameters:output_type -> concordium.v2.ChainParameters
	64, // 118: concordium.v2.Queries.GetBlockFinalizationSummary:output_type -> concordium.v2.BlockFinalizationSummary
	65, // 119: concordium.v2.Queries.GetBlockItems:output_type -> concordium.v2.BlockItem
	66, // 120: concordium.v2.Queries.GetBakersRewardPeriod:output_type -> concordium.v2.BakerRewardPeriodInfo
	67, // 121: concordium.v2.Queries.GetBlockCertificates:output_type -> concordium.v2.BlockCertificates
	68, // 122: concordium.v2.Queries.GetWinningBakersEpoch:output_type -> concordium.v2.WinningBaker
	30, // 123: concordium.v2.Queries.GetFirstBlockEpoch:output_type -> concordium.v2.BlockHash
	69, // 124: concordium.v2.Queries.GetConsensusDetailedStatus:output_type -> concordium.v2.ConsensusDetailedStatus
	70, // 125: concordium.v2.Queries.DryRun:output_type -> concordium.v2.DryRunResponse
	63, // [63:126] is the sub-list for method output_type
	0,  // [0:63] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_v2_concordium_service_proto_init() }
func file_v2_concordium_service_proto_init() {
	if File_v2_concordium_service_proto != nil {
		return
	}
	file_v2_concordium_kernel_proto_init()
	file_v2_concordium_types_proto_init()
	file_v2_concordium_protocol_level_tokens_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v2_concordium_service_proto_rawDesc), len(file_v2_concordium_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v2_concordium_service_proto_goTypes,
		DependencyIndexes: file_v2_concordium_service_proto_depIdxs,
	}.Build()
	File_v2_concordium_service_proto = out.File
	file_v2_concordium_service_proto_goTypes = nil
	file_v2_concordium_service_proto_depIdxs = nil
}
